version: "3"

services:
  #nginx
  scserver:
    container_name: scserver
    image: nginx:stable-alpine
    restart: always
    ports:
      - "6080:80"
    volumes:
      - ../html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scorpionet

  #php
  scapp:
    container_name: scapp
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: always
    volumes:
      - ../html:/var/www/html
    networks:
      - scorpionet
  # #db
  scdb:
    container_name: scdb
    platform: linux/x86_64
    image: mysql:8
    # ports:
    #   - 9586:3306
    volumes:
      - scdata:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: scorpio
      MYSQL_ROOT_PASSWORD: r00tadmin
    networks:
      - scorpionet

  scmyadmin:
    container_name: scmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: scdb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 6081:80
    networks:
      - scorpionet

volumes:
  scdata:
    driver: local

networks:
  scorpionet:
    name: scorpionet
