<!DOCTYPE html>
<html lang="<?= $scMetaLanguage ?>" dir="ltr" color-scheme="auto">

<head>
  <?php include 'layout/header.phtml'; ?>

  <link rel="stylesheet" href="/css/<?= $scMetaPath; ?>.css">
</head>

<body>

  <header>
    <?php include 'layout/navigation.phtml'; ?>

  </header>


  <?php include $page; ?>



  <footer>
    <?php include 'layout/footer.phtml' ?>
  </footer>

  <script src="/js/<?= $scMetaPath; ?>.js"></script>
</body>

</html>